### ISSUE TITLE
error

### ISSUE THREAD

**Issue by xiaolitongx** [HuangWBill/SVM-LSM-Toolbox#1]
Excuse me, what is the reason for this error in the model training module?
"ValueError: could not broadcast input array from shape (6912,) into shape (768,)"

**Comment by HuangWBill** [comment]
Hello, teachers and scholars!
Due to the change of my research direction and other reasons, I may not maintain the SVM-LSM Toolbox in the near future. If you have some problems that cannot be solved, you can join the WeChat group below (the QR code is valid for 7 days) to communicate and learn from each other. We deeply apologize for not being able to reply to your emails in time!

Wishing you all good luck in your research and good health!

SVM-LSM Toolbox Developer

10th August 2023
![58a5d95c205fa1e5f9963591a36eef1](https://github.com/HuangWBill/SVM-LSM-Toolbox/assets/76198298/7b18bfad-f03f-4977-b362-4bef282db381)
